[build]
command = "pnpm install && pnpm run build"

[site]
bucket = ".output"

[[routes]]
pattern = "/api/convert/uqload*"
zone_name = "samaflix.pages.dev"

[build.environment]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1" 