[build]
command = "pnpm install && pnpm run build && pnpm run pages:build"
pages_build_output_dir = ".next"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"

[build.processing]
skip_processing = true 