[build]
command = "pnpm install && pnpm run build"
pages_build_output_dir = ".next/standalone"

[build.environment]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1"

[site]
bucket = ".next"

[build.processing]
skip_processing = true 